import {
  Organization,
  Contributor,
  Contribution,
  Expense,
  FestivalEvent,
  CommitteeMember,
  AuditLog,
  User,
} from '@/types';

export const DEMO_ORGANIZATION: Organization = {
  id: 'org-asifabad-gandhichowk',
  name: 'Sri Ganesh Utsav Committee',
  slug: 'sri-ganesh-utsav-asifabad',
  organizerName: 'Gadam ArunKumar',
  contactNumber: '9848012345',
  location: {
    state: 'Telangana',
    district: 'Komaram Bheem Asifabad',
    village: 'Asifabad',
    area: 'Main Town',
    galli: 'Gandhi Chowk',
  },
  currentYear: 2026,
  years: [
    {
      id: 'year-2026',
      year: 2026,
      startDate: '2026-09-14',
      endDate: '2026-09-24',
      visarjanDate: '2026-09-24',
      chandaTarget: 200000,
      upiId: 'ganeshseva.asifabad@upi',
      isActive: true,
    },
    {
      id: 'year-2025',
      year: 2025,
      startDate: '2025-08-27',
      endDate: '2025-09-06',
      visarjanDate: '2025-09-06',
      chandaTarget: 175000,
      upiId: 'ganeshseva.asifabad@upi',
      isActive: false,
    },
    {
      id: 'year-2027',
      year: 2027,
      startDate: '2027-09-03',
      endDate: '2027-09-13',
      visarjanDate: '2027-09-13',
      chandaTarget: 250000,
      upiId: 'ganeshseva.asifabad@upi',
      isActive: false,
    },
  ],
  createdAt: '2026-01-10T10:00:00Z',
};

export const DEMO_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Gadam ArunKumar',
    email: 'arunkumar@ganeshseva.org',
    mobile: '9848012345',
    role: 'owner',
    committeeId: 'org-asifabad-gandhichowk',
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'user-2',
    name: 'Ramesh Reddy',
    email: 'ramesh.reddy@ganeshseva.org',
    mobile: '9848023456',
    role: 'admin',
    committeeId: 'org-asifabad-gandhichowk',
    createdAt: '2026-01-15T11:00:00Z',
  },
  {
    id: 'user-3',
    name: 'Suresh Kumar',
    email: 'suresh.kumar@ganeshseva.org',
    mobile: '9848034567',
    role: 'collector',
    committeeId: 'org-asifabad-gandhichowk',
    createdAt: '2026-02-01T09:00:00Z',
  },
  {
    id: 'user-4',
    name: 'Venkatesh Rao',
    email: 'venkatesh.rao@ganeshseva.org',
    mobile: '9848045678',
    role: 'viewer',
    committeeId: 'org-asifabad-gandhichowk',
    createdAt: '2026-02-05T14:30:00Z',
  },
];

export const DEMO_MEMBERS: CommitteeMember[] = [
  {
    id: 'mem-1',
    committeeId: 'org-asifabad-gandhichowk',
    userId: 'user-1',
    name: 'Gadam ArunKumar',
    phone: '9848012345',
    email: 'arunkumar@ganeshseva.org',
    role: 'owner',
    totalCollected: 45000,
    collectionCount: 18,
    joinedDate: '2026-01-10',
    isActive: true,
  },
  {
    id: 'mem-2',
    committeeId: 'org-asifabad-gandhichowk',
    userId: 'user-2',
    name: 'Ramesh Reddy',
    phone: '9848023456',
    email: 'ramesh.reddy@ganeshseva.org',
    role: 'admin',
    totalCollected: 38500,
    collectionCount: 15,
    joinedDate: '2026-01-15',
    isActive: true,
  },
  {
    id: 'mem-3',
    committeeId: 'org-asifabad-gandhichowk',
    userId: 'user-3',
    name: 'Suresh Kumar',
    phone: '9848034567',
    email: 'suresh.kumar@ganeshseva.org',
    role: 'collector',
    totalCollected: 27950,
    collectionCount: 14,
    joinedDate: '2026-02-01',
    isActive: true,
  },
  {
    id: 'mem-4',
    committeeId: 'org-asifabad-gandhichowk',
    name: 'Santosh Yadav',
    phone: '9848056789',
    email: 'santosh.yadav@ganeshseva.org',
    role: 'collector',
    totalCollected: 14000,
    collectionCount: 9,
    joinedDate: '2026-02-10',
    isActive: true,
  },
  {
    id: 'mem-5',
    committeeId: 'org-asifabad-gandhichowk',
    userId: 'user-4',
    name: 'Venkatesh Rao',
    phone: '9848045678',
    email: 'venkatesh.rao@ganeshseva.org',
    role: 'viewer',
    totalCollected: 0,
    collectionCount: 0,
    joinedDate: '2026-02-05',
    isActive: true,
  },
];

export const DEMO_CONTRIBUTORS: Contributor[] = [
  {
    id: 'ctb-1',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    name: 'K. Balakrishna',
    phone: '9849100101',
    address: 'H.No 3-45, Gandhi Chowk',
    totalDonated: 11116,
    totalPending: 0,
    contributionCount: 2,
    firstDonationDate: '2026-08-01',
    lastDonationDate: '2026-08-15',
  },
  {
    id: 'ctb-2',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    name: 'M. Srinivasulu',
    phone: '9849200202',
    address: 'Near Old Bus Stand, Gandhi Chowk',
    totalDonated: 10001,
    totalPending: 0,
    contributionCount: 1,
    firstDonationDate: '2026-08-05',
    lastDonationDate: '2026-08-05',
  },
  {
    id: 'ctb-3',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    name: 'T. Rajeshwar Rao',
    phone: '9849300303',
    address: 'Shop No 12, Main Bazaar',
    totalDonated: 7500,
    totalPending: 2500,
    contributionCount: 1,
    firstDonationDate: '2026-08-10',
    lastDonationDate: '2026-08-10',
  },
  {
    id: 'ctb-4',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    name: 'P. Nagender & Sons',
    phone: '9849400404',
    address: 'Cloth Merchant, Gandhi Chowk',
    totalDonated: 15000,
    totalPending: 0,
    contributionCount: 1,
    firstDonationDate: '2026-08-12',
    lastDonationDate: '2026-08-12',
  },
  {
    id: 'ctb-5',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    name: 'Dr. V. Ramana Murthy',
    phone: '9849500505',
    address: 'Shanti Clinic, Main Road',
    totalDonated: 10000,
    totalPending: 0,
    contributionCount: 1,
    firstDonationDate: '2026-08-14',
    lastDonationDate: '2026-08-14',
  },
  {
    id: 'ctb-6',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    name: 'Ch. Madhusudhan',
    phone: '9849600606',
    address: 'Galli No 2, Asifabad',
    totalDonated: 5116,
    totalPending: 0,
    contributionCount: 1,
    firstDonationDate: '2026-08-16',
    lastDonationDate: '2026-08-16',
  },
  {
    id: 'ctb-7',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    name: 'B. Satyanarayana',
    phone: '9849700707',
    address: 'Rice Mill Road',
    totalDonated: 5001,
    totalPending: 0,
    contributionCount: 1,
    firstDonationDate: '2026-08-18',
    lastDonationDate: '2026-08-18',
  },
  {
    id: 'ctb-8',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    name: 'G. Lingamurthy',
    phone: '9849800808',
    address: 'Teachers Colony',
    totalDonated: 3000,
    totalPending: 0,
    contributionCount: 1,
    firstDonationDate: '2026-08-20',
    lastDonationDate: '2026-08-20',
  },
  {
    id: 'ctb-9',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    name: 'V. Laxman Rao',
    phone: '9849900909',
    address: 'Court Road, Asifabad',
    totalDonated: 2500,
    totalPending: 0,
    contributionCount: 1,
    firstDonationDate: '2026-08-21',
    lastDonationDate: '2026-08-21',
  },
  {
    id: 'ctb-10',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    name: 'A. Gangadhar',
    phone: '9849011111',
    address: 'Auto Stand, Gandhi Chowk',
    totalDonated: 2116,
    totalPending: 0,
    contributionCount: 1,
    firstDonationDate: '2026-08-22',
    lastDonationDate: '2026-08-22',
  },
  {
    id: 'ctb-11',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    name: 'S. Prabhakar Reddy',
    phone: '9849022222',
    address: 'SBI Colony',
    totalDonated: 5000,
    totalPending: 5000,
    contributionCount: 1,
    firstDonationDate: '2026-08-22',
    lastDonationDate: '2026-08-22',
  },
  {
    id: 'ctb-12',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    name: 'D. Anjaiah Brothers',
    phone: '9849033333',
    address: 'Hardware Store, Gandhi Chowk',
    totalDonated: 8100,
    totalPending: 0,
    contributionCount: 1,
    firstDonationDate: '2026-08-23',
    lastDonationDate: '2026-08-23',
  },
];

export const DEMO_CONTRIBUTIONS: Contribution[] = [
  {
    id: 'cnt-1',
    receiptNumber: 'GS26-000241',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    contributorId: 'ctb-1',
    contributorName: 'K. Balakrishna',
    contributorPhone: '9849100101',
    amount: 10000,
    paidAmount: 10000,
    date: '2026-08-01',
    time: '10:30 AM',
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    collectorName: 'Gadam ArunKumar',
    collectorId: 'mem-1',
    notes: 'Main Pandal Sponsor Chanda',
    galli: 'Gandhi Chowk',
    createdAt: '2026-08-01T10:30:00Z',
  },
  {
    id: 'cnt-2',
    receiptNumber: 'GS26-000242',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    contributorId: 'ctb-2',
    contributorName: 'M. Srinivasulu',
    contributorPhone: '9849200202',
    amount: 10001,
    paidAmount: 10001,
    date: '2026-08-05',
    time: '11:15 AM',
    paymentMethod: 'Cash',
    paymentStatus: 'Paid',
    collectorName: 'Ramesh Reddy',
    collectorId: 'mem-2',
    notes: 'Ganesh Idol Seva Sponsor',
    galli: 'Gandhi Chowk',
    createdAt: '2026-08-05T11:15:00Z',
  },
  {
    id: 'cnt-3',
    receiptNumber: 'GS26-000243',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    contributorId: 'ctb-3',
    contributorName: 'T. Rajeshwar Rao',
    contributorPhone: '9849300303',
    amount: 10000,
    paidAmount: 7500,
    date: '2026-08-10',
    time: '04:45 PM',
    paymentMethod: 'UPI',
    paymentStatus: 'Partially Paid',
    collectorName: 'Suresh Kumar',
    collectorId: 'mem-3',
    notes: 'Balance 2500 promised on Sthapana Day',
    galli: 'Main Bazaar',
    createdAt: '2026-08-10T16:45:00Z',
  },
  {
    id: 'cnt-4',
    receiptNumber: 'GS26-000244',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    contributorId: 'ctb-4',
    contributorName: 'P. Nagender & Sons',
    contributorPhone: '9849400404',
    amount: 15000,
    paidAmount: 15000,
    date: '2026-08-12',
    time: '02:20 PM',
    paymentMethod: 'Bank Transfer',
    paymentStatus: 'Paid',
    collectorName: 'Gadam ArunKumar',
    collectorId: 'mem-1',
    notes: 'Annadanam Maha Prasadam Sponsorship',
    galli: 'Gandhi Chowk',
    createdAt: '2026-08-12T14:20:00Z',
  },
  {
    id: 'cnt-5',
    receiptNumber: 'GS26-000245',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    contributorId: 'ctb-5',
    contributorName: 'Dr. V. Ramana Murthy',
    contributorPhone: '9849500505',
    amount: 10000,
    paidAmount: 10000,
    date: '2026-08-14',
    time: '06:00 PM',
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    collectorName: 'Ramesh Reddy',
    collectorId: 'mem-2',
    notes: 'Lighting & Sound Seva',
    galli: 'Main Road',
    createdAt: '2026-08-14T18:00:00Z',
  },
  {
    id: 'cnt-6',
    receiptNumber: 'GS26-000246',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    contributorId: 'ctb-1',
    contributorName: 'K. Balakrishna',
    contributorPhone: '9849100101',
    amount: 1116,
    paidAmount: 1116,
    date: '2026-08-15',
    time: '09:00 AM',
    paymentMethod: 'Cash',
    paymentStatus: 'Paid',
    collectorName: 'Suresh Kumar',
    collectorId: 'mem-3',
    notes: 'Additional Pooja Material Contribution',
    galli: 'Gandhi Chowk',
    createdAt: '2026-08-15T09:00:00Z',
  },
  {
    id: 'cnt-7',
    receiptNumber: 'GS26-000247',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    contributorId: 'ctb-6',
    contributorName: 'Ch. Madhusudhan',
    contributorPhone: '9849600606',
    amount: 5116,
    paidAmount: 5116,
    date: '2026-08-16',
    time: '07:30 PM',
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    collectorName: 'Gadam ArunKumar',
    collectorId: 'mem-1',
    notes: 'Devotional Contribution',
    galli: 'Galli No 2',
    createdAt: '2026-08-16T19:30:00Z',
  },
  {
    id: 'cnt-8',
    receiptNumber: 'GS26-000248',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    contributorId: 'ctb-7',
    contributorName: 'B. Satyanarayana',
    contributorPhone: '9849700707',
    amount: 5001,
    paidAmount: 5001,
    date: '2026-08-18',
    time: '11:00 AM',
    paymentMethod: 'Cash',
    paymentStatus: 'Paid',
    collectorName: 'Santosh Yadav',
    collectorId: 'mem-4',
    notes: 'Maha Aarti Seva',
    galli: 'Rice Mill Road',
    createdAt: '2026-08-18T11:00:00Z',
  },
  {
    id: 'cnt-9',
    receiptNumber: 'GS26-000249',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    contributorId: 'ctb-8',
    contributorName: 'G. Lingamurthy',
    contributorPhone: '9849800808',
    amount: 3000,
    paidAmount: 3000,
    date: '2026-08-20',
    time: '05:15 PM',
    paymentMethod: 'Cash',
    paymentStatus: 'Paid',
    collectorName: 'Santosh Yadav',
    collectorId: 'mem-4',
    notes: 'Street collection',
    galli: 'Teachers Colony',
    createdAt: '2026-08-20T17:15:00Z',
  },
  {
    id: 'cnt-10',
    receiptNumber: 'GS26-000250',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    contributorId: 'ctb-9',
    contributorName: 'V. Laxman Rao',
    contributorPhone: '9849900909',
    amount: 2500,
    paidAmount: 2500,
    date: '2026-08-21',
    time: '03:40 PM',
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    collectorName: 'Ramesh Reddy',
    collectorId: 'mem-2',
    notes: 'Court Road chanda',
    galli: 'Court Road',
    createdAt: '2026-08-21T15:40:00Z',
  },
  {
    id: 'cnt-11',
    receiptNumber: 'GS26-000251',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    contributorId: 'ctb-10',
    contributorName: 'A. Gangadhar',
    contributorPhone: '9849011111',
    amount: 2116,
    paidAmount: 2116,
    date: '2026-08-22',
    time: '12:00 PM',
    paymentMethod: 'Cash',
    paymentStatus: 'Paid',
    collectorName: 'Suresh Kumar',
    collectorId: 'mem-3',
    notes: 'Auto Union Chanda',
    galli: 'Gandhi Chowk',
    createdAt: '2026-08-22T12:00:00Z',
  },
  {
    id: 'cnt-12',
    receiptNumber: 'GS26-000252',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    contributorId: 'ctb-11',
    contributorName: 'S. Prabhakar Reddy',
    contributorPhone: '9849022222',
    amount: 10000,
    paidAmount: 5000,
    date: '2026-08-22',
    time: '08:10 PM',
    paymentMethod: 'Cash',
    paymentStatus: 'Partially Paid',
    collectorName: 'Gadam ArunKumar',
    collectorId: 'mem-1',
    notes: 'Remaining 5000 to be paid on Visarjan',
    galli: 'SBI Colony',
    createdAt: '2026-08-22T20:10:00Z',
  },
  {
    id: 'cnt-13',
    receiptNumber: 'GS26-000253',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    contributorId: 'ctb-12',
    contributorName: 'D. Anjaiah Brothers',
    contributorPhone: '9849033333',
    amount: 8100,
    paidAmount: 8100,
    date: '2026-08-23',
    time: '01:30 PM',
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    collectorName: 'Ramesh Reddy',
    collectorId: 'mem-2',
    notes: 'Festival decoration material support',
    galli: 'Gandhi Chowk',
    createdAt: '2026-08-23T13:30:00Z',
  },
];

export const DEMO_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    expenseName: '11-Feet Clay Vinayaka Idol Advance',
    category: 'Ganesh Idol',
    amount: 22000,
    date: '2026-07-20',
    paidBy: 'Gadam ArunKumar',
    paymentMethod: 'UPI',
    notes: 'Dhoolpet idol maker booking advance',
    createdAt: '2026-07-20T10:00:00Z',
  },
  {
    id: 'exp-2',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    expenseName: 'Waterproof Grand Pandal Fabrication',
    category: 'Pandal',
    amount: 18000,
    date: '2026-08-10',
    paidBy: 'Ramesh Reddy',
    paymentMethod: 'Cash',
    notes: 'Iron frame and waterproof tarpaulin roofing',
    createdAt: '2026-08-10T14:00:00Z',
  },
  {
    id: 'exp-3',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    expenseName: 'LED Arch & Serial Lighting Setup',
    category: 'Lighting',
    amount: 9500,
    date: '2026-08-15',
    paidBy: 'Gadam ArunKumar',
    paymentMethod: 'UPI',
    notes: 'Gandhi Chowk main street welcome arch lights',
    createdAt: '2026-08-15T16:00:00Z',
  },
  {
    id: 'exp-4',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    expenseName: 'Digital Sound System & DJ for 9 Days',
    category: 'Sound',
    amount: 14000,
    date: '2026-08-18',
    paidBy: 'Ramesh Reddy',
    paymentMethod: 'UPI',
    notes: 'Full sound system, mic set, and devotional music setup',
    createdAt: '2026-08-18T11:00:00Z',
  },
  {
    id: 'exp-5',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    expenseName: 'Fresh Flowers, Garlands & Backdrop Cloth',
    category: 'Decoration',
    amount: 7500,
    date: '2026-08-20',
    paidBy: 'Suresh Kumar',
    paymentMethod: 'Cash',
    notes: 'Marigold and jasmine stage garland arrangement',
    createdAt: '2026-08-20T18:00:00Z',
  },
  {
    id: 'exp-6',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    expenseName: 'Puja Samagri, Camphor, Coconuts & Homam',
    category: 'Puja Materials',
    amount: 4800,
    date: '2026-08-22',
    paidBy: 'Gadam ArunKumar',
    paymentMethod: 'Cash',
    notes: 'Pooja items for Prana Pratishtha and 9 days daily aarti',
    createdAt: '2026-08-22T09:00:00Z',
  },
  {
    id: 'exp-7',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    expenseName: 'Idol Transportation from Hyderabad to Asifabad',
    category: 'Transportation',
    amount: 6500,
    date: '2026-08-23',
    paidBy: 'Ramesh Reddy',
    paymentMethod: 'UPI',
    notes: 'Trolley transport with cushion safety',
    createdAt: '2026-08-23T15:00:00Z',
  },
  {
    id: 'exp-8',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    expenseName: 'Temporary Electricity Meter & Board Approval',
    category: 'Electrical',
    amount: 3200,
    date: '2026-08-24',
    paidBy: 'Santosh Yadav',
    paymentMethod: 'Cash',
    notes: 'TSSPDCL festive commercial connection deposit',
    createdAt: '2026-08-24T12:00:00Z',
  },
];

export const DEMO_EVENTS: FestivalEvent[] = [
  {
    id: 'evt-1',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    eventName: 'Ganesh Sthapana & Prana Pratishtha',
    date: '2026-09-14',
    time: '08:30 AM',
    location: 'Gandhi Chowk Pandal',
    description: 'Veda pandit Ganapathi Homam and installation of 11-ft clay idol.',
    organizerInCharge: 'Gadam ArunKumar',
    isCompleted: false,
  },
  {
    id: 'evt-2',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    eventName: 'Maha Harathi & Modak Prasadam Distribution',
    date: '2026-09-14',
    time: '07:30 PM',
    location: 'Gandhi Chowk Pandal',
    description: 'Grand evening Aarti followed by distribution of 108 kg special modak prasadam.',
    organizerInCharge: 'Ramesh Reddy',
    isCompleted: false,
  },
  {
    id: 'evt-3',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    eventName: 'Children Devotional Singing & Fancy Dress Competition',
    date: '2026-09-17',
    time: '06:00 PM',
    location: 'Community Hall, Gandhi Chowk',
    description: 'Cultural competition for colony children with trophies and cash prizes.',
    organizerInCharge: 'Suresh Kumar',
    isCompleted: false,
  },
  {
    id: 'evt-4',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    eventName: 'Grand Annadanam (Maha Prasadam Feeding)',
    date: '2026-09-20',
    time: '12:30 PM',
    location: 'Gandhi Chowk Open Ground',
    description: 'Community feast serving over 2,500 devotees with traditional festive lunch.',
    organizerInCharge: 'Gadam ArunKumar & Ramesh Reddy',
    isCompleted: false,
  },
  {
    id: 'evt-5',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    eventName: 'Grand Laddu Auction & Visarjan Shobhayatra',
    date: '2026-09-24',
    time: '03:00 PM',
    location: 'Starts at Gandhi Chowk → Peddavagu River',
    description: 'Famous 21-kg Laddu auction followed by traditional Dappu, Kolatam & immersion procession.',
    organizerInCharge: 'All Committee Members',
    isCompleted: false,
  },
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    action: 'Committee Initialized',
    actorName: 'Gadam ArunKumar',
    actorRole: 'owner',
    details: 'Created Sri Ganesh Utsav Committee 2026 festival setup with ₹2,00,000 target',
    timestamp: '2026-01-10T10:00:00Z',
  },
  {
    id: 'aud-2',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    action: 'Chanda Collected',
    actorName: 'Gadam ArunKumar',
    actorRole: 'owner',
    details: 'Recorded ₹10,000 donation from K. Balakrishna (Receipt: GS26-000241)',
    timestamp: '2026-08-01T10:30:00Z',
  },
  {
    id: 'aud-3',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    action: 'Expense Added',
    actorName: 'Gadam ArunKumar',
    actorRole: 'owner',
    details: 'Added expense ₹22,000 for Ganesh Idol booking advance',
    timestamp: '2026-07-20T10:00:00Z',
  },
  {
    id: 'aud-4',
    committeeId: 'org-asifabad-gandhichowk',
    year: 2026,
    action: 'Chanda Collected',
    actorName: 'Ramesh Reddy',
    actorRole: 'admin',
    details: 'Recorded ₹10,001 donation from M. Srinivasulu (Receipt: GS26-000242)',
    timestamp: '2026-08-05T11:15:00Z',
  },
];
